name: Validate Files
on: 
  push:
  workflow_dispatch: 
jobs:
  file-validate:
    runs-on: "ubuntu-latest"

    steps: 
    - name: Get repo code on VM
      uses: actions/checkout@v4

    - name: validate html file
      run: test -f index.html

    - name: validate TSX file
      run: test -f src/main.tsx

    - name: validate TypeScript file
      run: test -f src/types.ts
