name: Validate Files
on: 
  push:
  workflow_dispatch: 
jobs:
  file-validate:
    runs-on: "ubuntu-latest"

    steps: 
    - name: Get repo code on VM
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: validate html file
      run: test -f index.html

    - name: validate TSX file
      run: test -f src/main.tsx

    - name: validate JavaScript file
      run: node --check script.js

    - name: validate css file
      run: npx vite build
